# Generated by Django 3.1 on 2023-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230404_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img_avatar.png', upload_to='userprofile'),
        ),
    ]
